'use strict';

/**
 * Map TTS phrases to pre-baked Supertonic WAV files.
 *
 * The plugin ships audio/<slug>.wav generated by scripts/generate-audio.py
 * for a fixed set of phrases. At runtime we look up the slug for the
 * phrase about to be spoken and play the WAV via System.Media.SoundPlayer.
 * If no slug matches or the WAV file is missing, callers fall back to
 * Windows SAPI (live synthesis) so unknown phrases and user-supplied
 * CLAUDE_NOTIFY_TTS_TEXT overrides still work.
 *
 * env: CLAUDE_NOTIFY_WAV_DISABLED=1 forces SAPI fallback for everything.
 */

const fs = require('fs');
const path = require('path');
const { readClaudeEnv } = require('./load-settings');

const AUDIO_DIR = path.resolve(__dirname, '..', '..', 'audio');

// Exact phrase strings used by pickPhrase() in notification-alert.js,
// stop-notify.js, and edge-pulse.ps1. Keep in sync with those callers.
const PHRASE_TO_SLUG = {
  'Plan ready': 'plan-ready',
  'Permission needed': 'permission-needed',
  'Claude is idle': 'claude-idle',
  'Claude is waiting': 'claude-waiting',
  'Claude has a question': 'claude-question',
  'Claude is done': 'claude-done',
  'Claude still needs you': 'claude-still-needs',
  'Bash permission needed': 'bash-permission',
};

// Verbs that have dedicated "Bash permission needed: <verb>" WAVs baked
// at generation time. Keeps the cadence natural — concatenating two WAVs
// at runtime introduces an unnatural pause.
const BAKED_BASH_VERBS = new Set([
  'rm', 'git', 'npm', 'docker', 'cd', 'ls', 'cat',
  'node', 'python', 'curl', 'ssh', 'mv', 'cp',
]);

function isDisabled() {
  return String(readClaudeEnv('CLAUDE_NOTIFY_WAV_DISABLED') || '').toLowerCase() === '1';
}

function slugForPhrase(text) {
  const direct = PHRASE_TO_SLUG[text];
  if (direct) return direct;
  const m = /^Bash permission needed:\s*(\S+)/.exec(String(text || ''));
  if (m && BAKED_BASH_VERBS.has(m[1].toLowerCase())) {
    return `bash-permission-${m[1].toLowerCase()}`;
  }
  return null;
}

function wavPathForSlug(slug) {
  if (!slug) return null;
  const p = path.join(AUDIO_DIR, `${slug}.wav`);
  return fs.existsSync(p) ? p : null;
}

/**
 * Build a PowerShell snippet that plays a pre-baked WAV synchronously via
 * System.Media.SoundPlayer. Returns null if no WAV is available for the
 * given phrase (caller should fall back to SAPI). PlaySync() blocks the
 * PS process — important because we wrap with the audio-duck snippet
 * (Spotify pauses BEFORE PlaySync, resumes AFTER).
 */
function buildPlayWavAction(text) {
  if (isDisabled()) return null;
  const slug = slugForPhrase(text);
  const wavPath = wavPathForSlug(slug);
  if (!wavPath) return null;
  const escaped = wavPath.replace(/'/g, "''");
  return `$p = New-Object System.Media.SoundPlayer '${escaped}'; $p.PlaySync(); $p.Dispose()`;
}

module.exports = {
  AUDIO_DIR,
  slugForPhrase,
  wavPathForSlug,
  buildPlayWavAction,
};
